Create DATABASE ASSIGNMENT1
USE ASSIGNMENT1;
CREATE TABLE EMPLOYEEee(
SSN int PRIMARY KEY ,
FNAME varchar(300) NOT NULL,
LNAME varchar(300) NOT NULL,
GENDER varchar (10)NOT NULL,
DNUM int ,
SUPERVISER varchar(30),
BIRTHDATE datetime 
);
Create TABLE DEPARTMENT(
DNUM  int PRIMARY KEY,
Dname varchar(20) NOT NULL,
Location nvarchar (40),
SSN int , 
HIRINGDATE date 
);
Create TABLE PROJECTS (
PNUM int PRIMARY KEY , 
PNAME  varchar ,
LOCATIONCITY nvarchar ,
Dnum int 
);
ALTER TABLE EMPLOYEEEE
ADD CONSTRAINT FK_EMP_DEPT
FOREIGN KEY (DNUM)
REFERENCES DEPARTMENT(DNUM);


ALTER TABLE EMPLOYEEEE
ALTER COLUMN SUPERVISER INT;

ALTER TABLE EMPLOYEEEE
ADD CONSTRAINT FK_EMP_SUPERVISOR
FOREIGN KEY (SUPERVISER)
REFERENCES EMPLOYEEEE(SSN);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_DEP_EMP
FOREIGN KEY (SSN)
REFERENCES EMPLOYEEEE(SSN);

ALTER TABLE PROJECTS
ADD CONSTRAINT FK_PRO_DEPT
FOREIGN KEY (DNUM)
REFERENCES DEPARTMENT(DNUM);

INSERT INTO EMPLOYEEEE (SSN, FNAME, LNAME, GENDER, DNUM, SUPERVISER, BIRTHDATE)
VALUES
(100, 'Nigm', 'Yasser', 'Male',   1, NULL, '2005-08-28'), 
(101, 'Sara',  'Ali',    'Female', 1, 100,  '1998-07-20'),
(102, 'kamar',  'Yasser', 'female',   1, 100,  '1997-02-05'),
(103, 'Mona',  'Kamal',  'Female', 2, NULL, '1994-11-30'), 
(104, 'Yousef','Adel',   'Male',   2, 103,  '1999-09-18');



INSERT INTO DEPARTMENT (DNUM, DNAME, LOCATION,SSN, HIRINGDATE)
VALUES
(1, 'IT', 'ISMAILIA', NULL, '2005-8-28'),
(2, 'HR', 'Giza', NULL, '2019-03-15'),
(3, 'Finance', 'CAIRO', NULL, '2021-07-28'
UPDATE EMPLOYEEee
SET DNUM =3
WHERE SSN IN (100,101);

CREATE TABLE DEPENDENT (
    DNAME VARCHAR(50) NOT NULL,
    GENDER VARCHAR(20) NOT NULL,
    BIRTHDATE DATE,
    ESSN INT NOT NULL,

    CONSTRAINT PK_DEPENDENT PRIMARY KEY (ESSN, DNAME),
    CONSTRAINT FK_DEPEN_EMP
        FOREIGN KEY (ESSN)
        REFERENCES EMPLOYEEEE(SSN)
        
);
INSERT INTO DEPENDENT (ESSN, DNAME, GENDER, BIRTHDATE)
VALUES
(100, 'MONA', 'Female', '2010-05-12'),
(100, 'Omar', 'Male', '2012-07-20'),
(101, 'YASSER ', 'Female', '2011-03-15'),
(102, 'Youssef', 'Male', '2009-09-18');

DELETE FROM DEPENDENT
WHERE ESSN = 101
  AND DNAME = 'MONA';
  SELECT SSN, FNAME, LNAME, GENDER, DNUM, SUPERVISER, BIRTHDATE
FROM EMPLOYEEEE
WHERE DNUM = 1;

CREATE TABLE WORKS_ON (
    ESSN INT NOT NULL,
    PNUM INT NOT NULL,
    WORKING_HOURS INT NOT NULL DEFAULT 0,
    PRIMARY KEY (ESSN, PNUM),
    CONSTRAINT FK_WORKS_EMP FOREIGN KEY (ESSN)
        REFERENCES EMPLOYEEEE(SSN),
        
    CONSTRAINT FK_WORKS_PROJ FOREIGN KEY (PNUM)
        REFERENCES PROJECTS(PNUM)
        
);

ALTER TABLE EMPLOYEEEE
ADD EMAIL VARCHAR(100) NULL;

ALTER TABLE EMPLOYEEEE
ALTER COLUMN FNAME VARCHAR(100) NOT NULL;



